MySQL_host: LocalHost
MySQL_port: 3306
MySQL_database: TeachingTutorials
MySQL_username: newuser1
MySQL_password: xxxx
Learning_Menu_Slot: 5
Compulsory_Tutorial: false
Compulsory_Tutorial_Promotion_Type: track
Compulsory_Tutorial_RankOld: default
Compulsory_Tutorial_RankNew: applicant
Compulsory_Tutorial_Track: builder
Compulsory_Tutorial_TrackOutline: default,applicant,apprentice,jrbuilder,builder,architect,reviewer
Lobby_TP_Type: Server
Server_Name: tutorials
Lobby_World:
Lobby_X:
Lobby_Y:
Lobby_Z:
Lobby_Pitch:
Lobby_Yaw:
Hologram_Max_Width: 40
Min_Y: -100