name: TeachingTutorials
version: '${project.version}'
main: teachingtutorials.TeachingTutorials
description: Provides a system for prospective builders of the Build the Earth project to learn skills
api-version: 1.18
author: George112n
database: true
commands:
  tutorials:
    usage: /<command>
    description: Deals will all tutorial related commands.
  blockspy:
    usage: /<command>
    description: Allows players to spy on other player's virtual blocks.
website: https://github.com/BTEUK/TeachingTutorials
softdepend:
  - DecentHolograms
  - Multiverse-Core
  - WorldGuard
  - FastAsyncWorldEdit