-- MySQL Script generated by MySQL Workbench
-- Fri Feb 11 21:12:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TeachingTutorials
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TeachingTutorials
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TeachingTutorials` DEFAULT CHARACTER SET utf8 ;
USE `TeachingTutorials` ;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeachingTutorials`.`Players` ;

CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Players` (
  `UUID` CHAR(36) NOT NULL,
  `CompletedCompulsory` TINYINT NOT NULL DEFAULT 0,
  `InLesson` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`UUID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Tutorials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeachingTutorials`.`Tutorials` ;

CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Tutorials` (
  `TutorialID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`TutorialID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeachingTutorials`.`Lessons` ;

CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Lessons` (
  `LessonID` INT NOT NULL AUTO_INCREMENT,
  `TutorialID` VARCHAR(45) NULL,
  `UUID` VARCHAR(45) NOT NULL,
  `Finished` TINYINT NOT NULL,
  `StageAt` INT NOT NULL,
  `StepAt` INT NOT NULL,
  PRIMARY KEY (`LessonID`),
  INDEX `User_idx` (`UUID` ASC) VISIBLE,
  CONSTRAINT `User`
    FOREIGN KEY (`UUID`)
    REFERENCES `TeachingTutorials`.`Players` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tutorial`
    FOREIGN KEY ()
    REFERENCES `TeachingTutorials`.`Tutorials` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeachingTutorials`.`CategoryPoints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeachingTutorials`.`CategoryPoints` ;

CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`CategoryPoints` (
  `TutorialID` INT NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  `MaxPoints` INT NOT NULL,
  PRIMARY KEY (`TutorialID`, `Category`, `MaxPoints`),
  CONSTRAINT `Tutorial`
    FOREIGN KEY (`TutorialID`)
    REFERENCES `TeachingTutorials`.`Tutorials` (`TutorialID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeachingTutorials`.`Locations` ;

CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Locations` (
  `LocationID` INT NOT NULL AUTO_INCREMENT,
  `TutorialID` INT NOT NULL,
  `Difficulty` FLOAT NOT NULL,
  PRIMARY KEY (`LocationID`),
  INDEX `Tutorial_idx` (`TutorialID` ASC) VISIBLE,
  CONSTRAINT `Tutorial`
    FOREIGN KEY (`TutorialID`)
    REFERENCES `TeachingTutorials`.`Tutorials` (`TutorialID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Stage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeachingTutorials`.`Stage` ;

CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Stage` (
  `StageID` INT NOT NULL,
  `TutorialID` INT NOT NULL,
  `Order` VARCHAR(45) NULL,
  PRIMARY KEY (`StageID`),
  INDEX `Tutorial_idx` (`TutorialID` ASC) VISIBLE,
  CONSTRAINT `Tutorial`
    FOREIGN KEY (`TutorialID`)
    REFERENCES `TeachingTutorials`.`Tutorials` (`TutorialID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Steps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeachingTutorials`.`Steps` ;

CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Steps` (
  `StepID` INT NOT NULL AUTO_INCREMENT,
  `Stage` INT NOT NULL,
  `StepInStage` INT NOT NULL,
  PRIMARY KEY (`StepID`),
  INDEX `Stage_idx` (`Stage` ASC) VISIBLE,
  CONSTRAINT `Stage`
    FOREIGN KEY (`Stage`)
    REFERENCES `TeachingTutorials`.`Stage` (`StageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Datas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeachingTutorials`.`Datas` ;

CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Datas` (
  `LocationID` INT NULL,
  `StepID` INT NULL,
  `Data` VARCHAR(45) NULL,
  INDEX `Location_idx` (`LocationID` ASC) VISIBLE,
  INDEX `Step_idx` (`StepID` ASC) VISIBLE,
  CONSTRAINT `Location`
    FOREIGN KEY (`LocationID`)
    REFERENCES `TeachingTutorials`.`Locations` (`LocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Step`
    FOREIGN KEY (`StepID`)
    REFERENCES `TeachingTutorials`.`Steps` (`StepID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
