-- MySQL Script generated by MySQL Workbench
-- Thu Jun 23 21:18:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- DROP TABLE IF EXISTS `TeachingTutorials`.`LocationTasks` ;
-- DROP TABLE IF EXISTS `TeachingTutorials`.`Scores` ;
-- DROP TABLE IF EXISTS `TeachingTutorials`.`Tasks` ;
-- DROP TABLE IF EXISTS `TeachingTutorials`.`Groups` ;
-- DROP TABLE IF EXISTS `TeachingTutorials`.`Steps` ;
-- DROP TABLE IF EXISTS `TeachingTutorials`.`Stages` ;
-- DROP TABLE IF EXISTS `TeachingTutorials`.`CategoryPoints` ;
-- DROP TABLE IF EXISTS `TeachingTutorials`.`Lessons` ;
-- DROP TABLE IF EXISTS `TeachingTutorials`.`Tutorials` ;
-- DROP TABLE IF EXISTS `TeachingTutorials`.`Locations` ;
-- DROP TABLE IF EXISTS `TeachingTutorials`.`Players` ;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Players` (
  `UUID` CHAR(36) NOT NULL,
  `CompletedCompulsory` TINYINT NOT NULL DEFAULT 0,
  `InLesson` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`UUID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Locations` (
  `LocationID` INT NOT NULL AUTO_INCREMENT,
  `Difficulty` FLOAT,
  `Latitude` DOUBLE NOT NULL,
  `Longitude` DOUBLE NOT NULL,
  `TutorialID` INT NOT NULL,
  PRIMARY KEY (`LocationID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Tutorials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Tutorials` (
  `TutorialID` INT NOT NULL AUTO_INCREMENT,
  `InUse` TINYINT NOT NULL DEFAULT 0,
  `TutorialName` VARCHAR(45) NOT NULL,
  `Compulsory` TINYINT NOT NULL DEFAULT 0,
  `Author` CHAR(36) NOT NULL,
  PRIMARY KEY (`TutorialID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Lessons` (
  `LessonID` INT NOT NULL AUTO_INCREMENT,
  `UUID` CHAR(36) NOT NULL,
  `TutorialID` INT NOT NULL,
  `Finished` TINYINT NOT NULL DEFAULT 0,
  `StageAt` INT NOT NULL DEFAULT 0,
  `StepAt` INT NOT NULL DEFAULT 0,
  `LocationID` INT NOT NULL,
  PRIMARY KEY (`LessonID`),
  CONSTRAINT `User`
    FOREIGN KEY (`UUID`)
    REFERENCES `TeachingTutorials`.`Players` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tutorial1`
    FOREIGN KEY (`TutorialID`)
    REFERENCES `TeachingTutorials`.`Tutorials` (`TutorialID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Location1`
    FOREIGN KEY (`LocationID`)
    REFERENCES `TeachingTutorials`.`Locations` (`LocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`CategoryPoints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`CategoryPoints` (
  `TutorialID` INT NOT NULL,
  `Category` ENUM('tpll', 'worldedit', 'colouring', 'detail', 'terraforming') NOT NULL,
  `Relevance` FLOAT NOT NULL,
  PRIMARY KEY (`TutorialID`, `Category`, `Relevance`),
  CONSTRAINT `Tutorial`
    FOREIGN KEY (`TutorialID`)
    REFERENCES `TeachingTutorials`.`Tutorials` (`TutorialID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Stages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Stages` (
  `StageID` INT NOT NULL AUTO_INCREMENT,
  `TutorialID` INT NOT NULL,
  `Order` INT NOT NULL,
  `StageName` VARCHAR(45) NULL,
  PRIMARY KEY (`StageID`),
  CONSTRAINT `Tutorial2`
    FOREIGN KEY (`TutorialID`)
    REFERENCES `TeachingTutorials`.`Tutorials` (`TutorialID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Steps` (
  `StepID` INT NOT NULL AUTO_INCREMENT,
  `StageID` INT NOT NULL,
  `StepInStage` INT NOT NULL,
  `StepName` VARCHAR(45) NULL,
  `StepInstructions` TEXT NULL,
  `InstructionDisplay` VARCHAR(45) NULL,
  PRIMARY KEY (`StepID`),
  CONSTRAINT `Stage`
    FOREIGN KEY (`StageID`)
    REFERENCES `TeachingTutorials`.`Stages` (`StageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Groups` (
  `GroupID` INT NOT NULL AUTO_INCREMENT,
  `StepID` INT NOT NULL,
  PRIMARY KEY (`GroupID`),
  CONSTRAINT `StepID`
    FOREIGN KEY (`StepID`)
    REFERENCES `TeachingTutorials`.`Steps` (`StepID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Tasks` (
  `TaskID` INT NOT NULL AUTO_INCREMENT,
  `GroupID` INT NOT NULL,
  `TaskType` VARCHAR(32) NULL,
  `Order` INT NOT NULL,
  `Details` VARCHAR(45) NULL,
  PRIMARY KEY (`TaskID`),
  CONSTRAINT `Group`
    FOREIGN KEY (`GroupID`)
    REFERENCES `TeachingTutorials`.`Groups` (`GroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Scores` (
  `LessonID` INT NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  `Score` INT NOT NULL,
  PRIMARY KEY (`LessonID`),
  CONSTRAINT `LessonID`
    FOREIGN KEY (`LessonID`)
    REFERENCES `TeachingTutorials`.`Lessons` (`LessonID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`LocationTasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`LocationTasks` (
  `LocationID` INT NOT NULL,
  `TaskID` INT NOT NULL,
  `Answers` MEDIUMTEXT NULL,
  `TpllDifficulty` FLOAT NULL,
  `WEDifficulty` FLOAT NULL,
  `ColouringDifficulty` FLOAT NULL,
  `DetailingDifficulty` FLOAT NULL,
  `TerraDifficulty` FLOAT NULL,
  CONSTRAINT `Location0`
    FOREIGN KEY (`LocationID`)
    REFERENCES `TeachingTutorials`.`Locations` (`LocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Task`
    FOREIGN KEY (`TaskID`)
    REFERENCES `TeachingTutorials`.`Tasks` (`TaskID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TeachingTutorials`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeachingTutorials`.`Events` (
  `UUID` CHAR(36) NOT NULL,
  `EventName` enum('COMPULSORY','CONTINUE','ADMIN_MENU') NOT NULL,
  `Timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ON UPDATE NO ACTION)
ENGINE = InnoDB;